"""
Dicionário de mapeamento de palavras-chave da linguagem Portulong para Python / discord.py.
"""

KEYWORDS_MAP = {
    "se": "if",
    "senao": "else",
    "senaose": "elif",
    "para": "for",
    "enquanto": "while",
    "definir": "def",
    "funcao": "def",
    "classe": "class",
    "importar": "import",
    "de": "from",
    "como": "as",
    "retornar": "return",
    "tentar": "try",
    "exceto": "except",
    "finalmente": "finally",
    "com": "with",
    "lambda": "lambda",
    "passar": "pass",
    "parar": "break",
    "continuar": "continue",
    "Verdadeiro": "True",
    "Falso": "False",
    "Nulo": "None",
    "e": "and",
    "ou": "or",
    "nao": "not",
    "em": "in",
    "eh": "is",
    "nao_eh": "is not",
    "asseverar": "assert",
    "global": "global",
    "naolocal": "nonlocal",
    "levantar": "raise",
    "produzir": "yield",
    "assincrono": "async",
    "aguardar": "await",
}

BUILTINS_MAP = {
    "escrever": "print",
    "mostrar": "print",
    "ler": "input",
    "tamanho": "len",
    "inteiro": "int",
    "texto": "str",
    "real": "float",
    "decimal": "float",
    "boleano": "bool",
    "lista": "list",
    "dicionario": "dict",
    "conjunto": "set",
    "tupla": "tuple",
    "intervalo": "range",
    "abrir": "open",
    "tipo": "type",
    "somar": "sum",
    "absoluto": "abs",
    "maximo": "max",
    "minimo": "min",
    "arredondar": "round",
    "mapear": "map",
    "filtrar": "filter",
    "ordenado": "sorted",
    "super": "super",
    "propriedade": "property",
    "zipar": "zip",
    "enumerar": "enumerate",
    "objeto": "object",
    "qualquer": "any",
    "todos": "all",
    "ajuda": "help",
    "identidade": "id",
    "reversivel": "reversed",
    "formatar": "format",
    "obter_atributo": "getattr",
    "definir_atributo": "setattr",
    "tem_atributo": "hasattr",
    "excluir_atributo": "delattr",
    "representacao": "repr",
    "proximo": "next",
    "iterador": "iter",
    "eh_instancia": "isinstance",
    "eh_subclasse": "issubclass",
    
    # Python Core Exceptions
    "Excessao": "Exception",
    "ErroDeValor": "ValueError",
    "ErroDeTipo": "TypeError",
    "ErroDeNome": "NameError",
    "ErroDeIndice": "IndexError",
    "ErroDeChave": "KeyError",
    "ErroDeImportacao": "ImportError",
    "ErroDeAtributo": "AttributeError",
    "ErroDivisaoPorZero": "ZeroDivisionError",
    "FaltaDeMemoria": "MemoryError",
    "ParadaDeIteracao": "StopIteration",
    "ErroDoSistema": "OSError",
    "ArquivoNaoEncontrado": "FileNotFoundError",
    "InterrupcaoPeloTeclado": "KeyboardInterrupt",
    "ErroDeAsseveracao": "AssertionError",
    "ErroDeExecucao": "RuntimeError",
    "ErroNaoImplementado": "NotImplementedError",
}

